# Compute clustering statistics for OC clustering with Leiden (laptop)
library(xtable)
library(data.table)
rm(list=ls())
setwd('~/Desktop/SNAP')
nc_denom <- 75025194 # From postgres nodelist

# clustering files sftp'ed from /data2/open_citations on odesa Jan 13, 2023
# files were generated by subset_graph_nonetworkit.R script on Leiden clustering outputs

fl <- list.files(pattern='*trimmed_treecounts.tsv')
file_list = list()
for(i in 1:length(fl)) {
	file_list[[i]] <- fread(fl[[i]])
}
names(file_list) <- fl



xtable(rbindlist(lapply(file_list,FUN=function(x) x[,.(clus_count=length(node_count),node_cov=round(100*sum(node_count)/nc_denom,2),min=min(node_count),med=median(node_count),max=max(node_count))])))

